language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jhillieritrs/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jhillieritrs/docker-react npm run test